Update to latest

diff --git a/.github/actions/templates/avm-validateModuleDeployment/action.yml b/.github/actions/templates/avm-validateModuleDeployment/action.yml
--- a/.github/actions/templates/avm-validateModuleDeployment/action.yml
+++ b/.github/actions/templates/avm-validateModuleDeployment/action.yml
@@ -246,196 +246,212 @@ runs:
 
     # [Deployment execution] task(s)
     # ------------------------------
-    # - name: "Deploy template file"
-    #   id: deploy_step
-    #   uses: azure/powershell@v2
-    #   with:
-    #     azPSVersion: "latest"
-    #     inlineScript: |
-    #       # Grouping task logs
-    #       Write-Output '::group::Deploy template file'
+    - name: "Deploy template file"
+      id: deploy_step
+      uses: azure/powershell@v2
+      with:
+        azPSVersion: "latest"
+        inlineScript: |
+          # Grouping task logs
+          Write-Output '::group::Deploy template file'
 
-    #       # Load used functions
-    #       . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'e2eValidation' 'resourceDeployment' 'New-TemplateDeployment.ps1')
+          # Load used functions
+          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'e2eValidation' 'resourceDeployment' 'New-TemplateDeployment.ps1')
 
-    #       # Prepare general parameters
-    #       # --------------------------
-    #       $subscriptionId = '${{ inputs.subscriptionId }}'
-    #       $managementGroupId = '${{ inputs.managementGroupId }}'
+          # Prepare general parameters
+          # --------------------------
+          $subscriptionId = '${{ inputs.subscriptionId }}'
+          $managementGroupId = '${{ inputs.managementGroupId }}'
 
-    #       # Resolve template file path
-    #       $moduleTestFilePath = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
+          # Resolve template file path
+          $moduleTestFilePath = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
 
-    #       # Determine possible parameters depending on file type
-    #       if ((Split-Path $moduleTestFilePath -Extension) -eq '.bicep') {
-    #         $moduleTemplateContent = bicep build $moduleTestFilePath --stdout | ConvertFrom-Json -AsHashtable
-    #         $moduleTemplatePossibleParameters = $moduleTemplateContent.parameters.Keys
-    #       } else {
-    #         $moduleTemplatePossibleParameters = ((Get-Content $moduleTestFilePath -Raw) | ConvertFrom-Json -AsHashtable).parameters.keys
-    #       }
+          # Determine possible parameters depending on file type
+          if ((Split-Path $moduleTestFilePath -Extension) -eq '.bicep') {
+            $moduleTemplateContent = bicep build $moduleTestFilePath --stdout | ConvertFrom-Json -AsHashtable
+            $moduleTemplatePossibleParameters = $moduleTemplateContent.parameters.Keys
+          } else {
+            $moduleTemplatePossibleParameters = ((Get-Content $moduleTestFilePath -Raw) | ConvertFrom-Json -AsHashtable).parameters.keys
+          }
 
-    #       # ----------------- #
-    #       # Invoke deployment #
-    #       # ----------------- #
-    #       $functionInput = @{
-    #         TemplateFilePath           = $moduleTestFilePath
-    #         DeploymentMetadataLocation = '${{ inputs.deploymentMetadataLocation }}'
-    #         SubscriptionId             = $subscriptionId
-    #         ManagementGroupId          = $managementGroupId
-    #         DoNotThrow                 = $true
-    #         RepoRoot                   = $env:GITHUB_WORKSPACE
-    #         AdditionalParameters       = @{}
-    #       }
+          # ----------------- #
+          # Invoke deployment #
+          # ----------------- #
+          $functionInput = @{
+            TemplateFilePath           = $moduleTestFilePath
+            DeploymentMetadataLocation = '${{ inputs.deploymentMetadataLocation }}'
+            SubscriptionId             = $subscriptionId
+            ManagementGroupId          = $managementGroupId
+            DoNotThrow                 = $true
+            RepoRoot                   = $env:GITHUB_WORKSPACE
+            AdditionalParameters       = @{}
+          }
 
-    #       if($moduleTemplatePossibleParameters -contains 'resourceLocation') {
-    #         $functionInput.AdditionalParameters += @{
-    #           resourceLocation = '${{ steps.get-resource-location.outputs.resourceLocation }}'
-    #         }
-    #       }
-    #       if($moduleTemplatePossibleParameters -contains 'baseTime') {
-    #         $functionInput.AdditionalParameters += @{
-    #           baseTime = (Get-Date).ToString('u') # Setting base time explicitly so that any potential retry will reuse the same timestamp
-    #         }
-    #       }
+          if($moduleTemplatePossibleParameters -contains 'resourceLocation') {
+            $functionInput.AdditionalParameters += @{
+              resourceLocation = '${{ steps.get-resource-location.outputs.resourceLocation }}'
+            }
+          }
+          if($moduleTemplatePossibleParameters -contains 'baseTime') {
+            $functionInput.AdditionalParameters += @{
+              baseTime = (Get-Date).ToString('u') # Setting base time explicitly so that any potential retry will reuse the same timestamp
+            }
+          }
 
-    #       Write-Verbose 'Invoke task with' -Verbose
-    #       Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose
+          # Fetch & addd custom secrets, if any
+          # -----------------------------------
+          $keyVaultName = "${{ env.KEY_VAULT_NAME }}"
+          # Note: Also requires at least Key Vault Secrets User role assignment
+          $customKeyVaultSecrets = Get-AzKeyVaultSecret -VaultName $keyVaultName | Where-Object { $_.Name -match '^CUSTOM-.+' }
 
-    #       # Invoke deployment
-    #       $res = New-TemplateDeployment @functionInput -Verbose
+          foreach($customSecret in $customKeyVaultSecrets) {
+            $formattedName = $customSecret.Name -replace '^CUSTOM-' # e.g. 'CUSTOM-mySecret' -> 'mySecret'
+            if($moduleTemplatePossibleParameters -contains $formattedName) {
+              Write-Verbose ('Setting value for parameter [{0}]' -f $formattedName) -Verbose
+              $functionInput.AdditionalParameters += @{
+                $formattedName = (Get-AzKeyVaultSecret -VaultName $keyVaultName -Name $customSecret.Name).SecretValue
+              }
+            }
+          }
 
-    #       # Get deployment name
-    #       Write-Output ('{0}={1}' -f 'deploymentNames', ($res.deploymentNames | ConvertTo-Json -Compress)) >> $env:GITHUB_OUTPUT
+          Write-Verbose 'Invoke task with' -Verbose
+          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose
 
-    #       # Populate further outputs
-    #       $deploymentOutput = $res.deploymentOutput | ConvertTo-Json -Depth 99 -Compress
-    #       Write-Output ('{0}={1}' -f 'deploymentOutput', $deploymentOutput) >> $env:GITHUB_OUTPUT
+          # Invoke deployment
+          $res = New-TemplateDeployment @functionInput -Verbose
 
-    #       Write-Verbose "Deployment output: $deploymentOutput" -Verbose
+          # Get deployment name
+          Write-Output ('{0}={1}' -f 'deploymentNames', ($res.deploymentNames | ConvertTo-Json -Compress)) >> $env:GITHUB_OUTPUT
 
-    #       if ($res.ContainsKey('exception')) {
-    #         # Happens only if there is an exception
-    #         throw $res.exception
-    #       }
+          # Populate further outputs
+          $deploymentOutput = $res.deploymentOutput | ConvertTo-Json -Depth 99 -Compress
+          Write-Output ('{0}={1}' -f 'deploymentOutput', $deploymentOutput) >> $env:GITHUB_OUTPUT
 
-    #       Write-Output '::endgroup::'
+          Write-Verbose "Deployment output: $deploymentOutput" -Verbose
 
-    # # [Post-Deployment test] task(s)
-    # # ------------------------------
-    # - name: "Run post-deployment Pester tests"
-    #   id: pester_run_step
-    #   shell: pwsh
-    #   run: |
-    #     # Grouping task logs
-    #     Write-Output '::group::Run Pester tests'
+          if ($res.ContainsKey('exception')) {
+            # Happens only if there is an exception
+            throw $res.exception
+          }
 
-    #     # Load used functions
-    #     . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'staticValidation' 'compliance' 'Set-PesterGitHubOutput.ps1')
+          Write-Output '::endgroup::'
 
-    #     # Set repo root path
-    #     $repoRootPath = $env:GITHUB_WORKSPACE
+    # [Post-Deployment test] task(s)
+    # ------------------------------
+    - name: "Run post-deployment Pester tests"
+      id: pester_run_step
+      shell: pwsh
+      run: |
+        # Grouping task logs
+        Write-Output '::group::Run Pester tests'
 
-    #     $moduleTestFilePath = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
-    #     $moduleTestFolderPath = Split-Path $moduleTestFilePath
-    #     $moduleTestFolderName = Split-Path $moduleTestFolderPath -Leaf
+        # Load used functions
+        . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'staticValidation' 'compliance' 'Set-PesterGitHubOutput.ps1')
 
-    #     $deploymentOutputs = '${{ steps.deploy_step.outputs.deploymentOutput }}' | ConvertFrom-Json -AsHashTable
+        # Set repo root path
+        $repoRootPath = $env:GITHUB_WORKSPACE
 
-    #     # --------------------- #
-    #     # Invoke Pester test(s) #
-    #     # --------------------- #
+        $moduleTestFilePath = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
+        $moduleTestFolderPath = Split-Path $moduleTestFilePath
+        $moduleTestFolderName = Split-Path $moduleTestFolderPath -Leaf
 
-    #     $pesterConfiguration = @{
-    #       Run    = @{
-    #         Container = New-PesterContainer -Path $moduleTestFolderPath -Data @{
-    #           TestInputData = @{
-    #             DeploymentOutputs    = $deploymentOutputs    # Passing in in case we want to directly validate data via the deployment's output
-    #             ModuleTestFolderPath = $moduleTestFolderPath # Passing in in case we want to access any data in the test folder / files
-    #           }
-    #         }
-    #         PassThru  = $true
-    #       }
-    #       Output = @{
-    #         Verbosity = 'Detailed'
-    #       }
-    #     }
+        $deploymentOutputs = '${{ steps.deploy_step.outputs.deploymentOutput }}' | ConvertFrom-Json -AsHashTable
 
-    #     Write-Verbose 'Invoke test with' -Verbose
-    #     $foundTestPaths = $pesterConfiguration.Run.Container | Where-Object { -not [String]::IsNullOrEmpty($_.Item.FullName) } | Foreach-Object { ($_.Item.FullName -split '[\\|\/]tests[\\|\/]e2e[\\|\/]')[1] }
+        # --------------------- #
+        # Invoke Pester test(s) #
+        # --------------------- #
 
-    #     if($foundTestPaths.Count -gt 0) {
-    #       Write-Verbose ('Path(s): {0}' -f ($foundTestPaths | Convertto-Json)) -Verbose
-    #       Write-Verbose ('Data: {0}' -f ($pesterConfiguration.Run.Container.Data[0] | ConvertTo-Json -Depth 3)) -Verbose
+        $pesterConfiguration = @{
+          Run    = @{
+            Container = New-PesterContainer -Path $moduleTestFolderPath -Data @{
+              TestInputData = @{
+                DeploymentOutputs    = $deploymentOutputs    # Passing in in case we want to directly validate data via the deployment's output
+                ModuleTestFolderPath = $moduleTestFolderPath # Passing in in case we want to access any data in the test folder / files
+              }
+            }
+            PassThru  = $true
+          }
+          Output = @{
+            Verbosity = 'Detailed'
+          }
+        }
 
-    #       $testResults = Invoke-Pester -Configuration $pesterConfiguration
+        Write-Verbose 'Invoke test with' -Verbose
+        $foundTestPaths = $pesterConfiguration.Run.Container | Where-Object { -not [String]::IsNullOrEmpty($_.Item.FullName) } | Foreach-Object { ($_.Item.FullName -split '[\\|\/]tests[\\|\/]e2e[\\|\/]')[1] }
 
-    #       # ----------------------------------------- #
-    #       # Create formatted Pester Test Results File #
-    #       # ----------------------------------------- #
+        if($foundTestPaths.Count -gt 0) {
+          Write-Verbose ('Path(s): {0}' -f ($foundTestPaths | Convertto-Json)) -Verbose
+          Write-Verbose ('Data: {0}' -f ($pesterConfiguration.Run.Container.Data[0] | ConvertTo-Json -Depth 3)) -Verbose
 
-    #       $functionInput = @{
-    #         PesterTestResults = $testResults
-    #         OutputFilePath    = Join-Path $env:GITHUB_WORKSPACE 'avm' "$moduleTestFolderName-Pester-output.md"
-    #         GitHubRepository  = $env:GITHUB_REPOSITORY
-    #         BranchName        = $env:GITHUB_REF
-    #         Title             = 'Pester post-deployment validation summary'
-    #       }
+          $testResults = Invoke-Pester -Configuration $pesterConfiguration
 
-    #       Write-Verbose 'Invoke Pester formatting function with' -Verbose
-    #       Write-Verbose ($functionInput | ConvertTo-Json -Depth 0 | Out-String) -Verbose
+          # ----------------------------------------- #
+          # Create formatted Pester Test Results File #
+          # ----------------------------------------- #
 
-    #       Set-PesterGitHubOutput @functionInput -Verbose
+          $functionInput = @{
+            PesterTestResults = $testResults
+            OutputFilePath    = Join-Path $env:GITHUB_WORKSPACE 'avm' "$moduleTestFolderName-Pester-output.md"
+            GitHubRepository  = $env:GITHUB_REPOSITORY
+            BranchName        = $env:GITHUB_REF
+            Title             = 'Pester post-deployment validation summary'
+          }
 
-    #       Write-Output ('{0}={1}' -f 'formattedPesterResultsPath', $functionInput.outputFilePath) >> $env:GITHUB_OUTPUT
-    #     } else {
-    #       Write-Verbose 'Found no Pester test files (*.test.ps1) in test folder' -Verbose
-    #       Write-Output ('{0}={1}' -f 'formattedPesterResultsPath', '') >> $env:GITHUB_OUTPUT
-    #     }
-    # - name: "Output to GitHub job summaries"
-    #   if: steps.pester_run_step.outputs.formattedPesterResultsPath != ''
-    #   shell: pwsh
-    #   run: |
-    #     # Grouping task logs
-    #     Write-Output '::group::Output to GitHub job summaries'
+          Write-Verbose 'Invoke Pester formatting function with' -Verbose
+          Write-Verbose ($functionInput | ConvertTo-Json -Depth 0 | Out-String) -Verbose
 
-    #     $mdPesterOutputFilePath = '${{ steps.pester_run_step.outputs.formattedPesterResultsPath }}'
+          Set-PesterGitHubOutput @functionInput -Verbose
 
-    #     if (-not (Test-Path $mdPesterOutputFilePath)) {
-    #       Write-Warning ('Input file [{0}] not found. Please check if the previous task threw an error and try again.' -f $mdPesterOutputFilePath)
-    #     } else {
-    #       Get-Content $mdPesterOutputFilePath >> $env:GITHUB_STEP_SUMMARY
-    #       Write-Verbose ('Successfully printed out file [{0}] to Job Summaries' -f $mdPesterOutputFilePath) -Verbose
-    #     }
+          Write-Output ('{0}={1}' -f 'formattedPesterResultsPath', $functionInput.outputFilePath) >> $env:GITHUB_OUTPUT
+        } else {
+          Write-Verbose 'Found no Pester test files (*.test.ps1) in test folder' -Verbose
+          Write-Output ('{0}={1}' -f 'formattedPesterResultsPath', '') >> $env:GITHUB_OUTPUT
+        }
+    - name: "Output to GitHub job summaries"
+      if: steps.pester_run_step.outputs.formattedPesterResultsPath != ''
+      shell: pwsh
+      run: |
+        # Grouping task logs
+        Write-Output '::group::Output to GitHub job summaries'
 
-    #     Write-Output '::endgroup::'
+        $mdPesterOutputFilePath = '${{ steps.pester_run_step.outputs.formattedPesterResultsPath }}'
 
-    # # [Deployment removal] task(s)
-    # # ----------------------------
-    # - name: "Remove deployed resources"
-    #   if: ${{ (success() || failure()) && inputs.removeDeployment == 'true' && steps.deploy_step.outputs.deploymentNames != '' }}
-    #   uses: azure/powershell@v2
-    #   with:
-    #     azPSVersion: "latest"
-    #     inlineScript: |
-    #       # Grouping task logs
-    #       Write-Output '::group::Remove deployed resources'
+        if (-not (Test-Path $mdPesterOutputFilePath)) {
+          Write-Warning ('Input file [{0}] not found. Please check if the previous task threw an error and try again.' -f $mdPesterOutputFilePath)
+        } else {
+          Get-Content $mdPesterOutputFilePath >> $env:GITHUB_STEP_SUMMARY
+          Write-Verbose ('Successfully printed out file [{0}] to Job Summaries' -f $mdPesterOutputFilePath) -Verbose
+        }
 
-    #       # Load used function
-    #       . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'e2eValidation' 'resourceRemoval' 'Initialize-DeploymentRemoval.ps1')
+        Write-Output '::endgroup::'
 
-    #       $functionInput = @{
-    #         TemplateFilePath  = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
-    #         DeploymentNames   = '${{ steps.deploy_step.outputs.deploymentNames }}' | ConvertFrom-Json
-    #         ManagementGroupId = '${{ inputs.managementGroupId }}'
-    #       }
+    # [Deployment removal] task(s)
+    # ----------------------------
+    - name: "Remove deployed resources"
+      if: ${{ (success() || failure()) && inputs.removeDeployment == 'true' && steps.deploy_step.outputs.deploymentNames != '' }}
+      uses: azure/powershell@v2
+      with:
+        azPSVersion: "latest"
+        inlineScript: |
+          # Grouping task logs
+          Write-Output '::group::Remove deployed resources'
 
-    #       if (-not [String]::IsNullOrEmpty('${{ inputs.subscriptionId }}')) {
-    #           $functionInput['SubscriptionId'] = '${{ inputs.subscriptionId }}'
-    #       }
+          # Load used function
+          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'e2eValidation' 'resourceRemoval' 'Initialize-DeploymentRemoval.ps1')
 
-    #       Write-Verbose 'Invoke task with' -Verbose
-    #       Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose
+          $functionInput = @{
+            TemplateFilePath  = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
+            DeploymentNames   = '${{ steps.deploy_step.outputs.deploymentNames }}' | ConvertFrom-Json
+            ManagementGroupId = '${{ inputs.managementGroupId }}'
+          }
 
-    #       Initialize-DeploymentRemoval @functionInput
+          if (-not [String]::IsNullOrEmpty('${{ inputs.subscriptionId }}')) {
+              $functionInput['SubscriptionId'] = '${{ inputs.subscriptionId }}'
+          }
 
-    #       Write-Output '::endgroup::'
+          Write-Verbose 'Invoke task with' -Verbose
+          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose
+
+          Initialize-DeploymentRemoval @functionInput
+
+          Write-Output '::endgroup::'
