Validate publish is successful

diff --git a/.github/workflows/publish-module.yml b/.github/workflows/publish-module.yml
--- a/.github/workflows/publish-module.yml
+++ b/.github/workflows/publish-module.yml
@@ -71,3 +71,56 @@ jobs:
 
       - name: Publish module
         run: bicep publish "modules/${{ steps.parse-tag.outputs.module_path }}/main.json" --target "br:${{ secrets.PUBLISH_REGISTRY_SERVER }}/public/bicep/${{ steps.parse-tag.outputs.module_path }}:${{ steps.parse-tag.outputs.version }}" --documentationUri "${{ steps.parse-tag.outputs.documentation_uri }}" --force
+
+      - name: Validate publish
+        run: |
+          Version="${{ steps.parse-tag.outputs.version }}"
+          ModulePath="${{ steps.parse-tag.outputs.module_path }}"
+
+          time_limit_seconds=30
+          end_time=$((SECONDS+time_limit_seconds))
+          retry_seconds=5
+
+          while true; do
+            CATALOG=https://mcr.microsoft.com/v2/_catalog
+            echo curl -sLo catalog $CATALOG
+            curl -sLo catalog $CATALOG
+            cat catalog | fgrep "bicep/" > bicepcatalog
+            echo "Bicep modules found in MCR catalog:"
+            cat bicepcatalog
+
+            if fgrep -q "\"bicep/$ModulePath\"" catalog; then
+              echo "Passed: Found module $ModulePath in the MCR catalog"
+              break
+            else
+              echo "Error: Module $ModulePath is not in the MCR catalog. Retrying in $retry_seconds seconds"
+              sleep $retry_seconds
+            fi
+
+            if [ $SECONDS -ge $end_time ]; then
+              echo "Time limit reached. Failed to validate publish within the specified time."
+              exit 1
+            fi
+          done
+
+          while true; do
+            TAGS=https://mcr.microsoft.com/v2/bicep/ai/cognitiveservices/tags/list
+            echo curl -sLo tags $TAGS
+            curl -sLo tags $TAGS
+            echo "Tags:"
+            cat tags
+
+            echo
+            if fgrep -q "$Version" tags; then
+              echo "Passed: Found new tag $Version for published module"
+              break
+            else
+              echo "Error: Coud not find new tag $Version for published module. Retrying in $retry_seconds seconds"
+              sleep $retry_seconds
+            fi
+
+            if [ $SECONDS -ge $end_time ]; then
+              echo "Time limit reached. Failed to validate publish within the specified time."
+              exit 1
+            fi
+          done
